# Generated by Django 5.1.3 on 2025-07-21 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_is_completed_project_is_submitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_time_tracked',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
