# Generated by Django 5.1.3 on 2025-07-21 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_total_time_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_time_tracked',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
