# Generated by Django 5.1.3 on 2025-07-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_total_time_tracked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='total_time_tracked',
            new_name='tracked_time',
        ),
    ]
