# Generated by Django 5.1.3 on 2025-07-21 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_total_time_tracked_project_tracked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tracked_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
