# Generated by Django 5.1.3 on 2025-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_tracked_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='submitted_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tracked_time',
        ),
        migrations.AddField(
            model_name='project',
            name='is_timer_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='total_tracked_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='hours_assigned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
