# Generated by Django 5.1.3 on 2025-07-21 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_submitted_at_project_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='start_time',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_timer_running',
        ),
        migrations.RemoveField(
            model_name='project',
            name='total_tracked_seconds',
        ),
        migrations.AddField(
            model_name='project',
            name='tracked_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='hours_assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
