# Generated by Django 5.1.3 on 2025-07-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasktimer_user_alter_worksession_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktimer',
            name='user',
        ),
        migrations.AddField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='tasks.task'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubmittedTask',
        ),
    ]
