# Generated by Django 5.1.3 on 2025-07-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_tasktimer_user_worksession_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hours_assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
