# Generated by Django 5.1.3 on 2025-07-14 11:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_hours_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktimer',
            name='total_tracked_seconds',
        ),
        migrations.AlterField(
            model_name='tasktimer',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 14, 11, 35, 0, 46927, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktimer',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasktimer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_timers', to='tasks.task'),
        ),
    ]
