# Generated by Django 5.1.3 on 2025-07-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignTasks', '0007_remove_assignedtask_user_assignedtask_users'),
        ('tasks', '0005_remove_tasktimer_total_tracked_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssignTasks.assignedtask'),
        ),
    ]
