# Generated by Django 5.1.3 on 2025-07-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_worksession_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
