# Generated by Django 5.1.3 on 2025-07-16 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_worksession_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktimer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='tasks.task'),
        ),
    ]
