# Generated by Django 5.1.3 on 2025-07-08 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssignTasks', '0002_tasksubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
    ]
