# Generated by Django 5.1.3 on 2025-07-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignTasks', '0005_delete_submittedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='hours_assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
