# Generated by Django 5.1.3 on 2025-07-15 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssignTasks', '0006_assignedtask_hours_assigned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtask',
            name='user',
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='users',
            field=models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
