# Generated by Django 5.1.3 on 2025-07-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0007_alter_worksession_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedTask',
            fields=[
            ],
            options={
                'verbose_name': 'Submitted Task',
                'verbose_name_plural': 'Submitted Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
    ]
