
name: Manual Deployment

on:
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Execute remote SSH commands in the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME || 'ubuntu' }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            set -Eeuo pipefail
            APP_DIR="/home/ubuntu/ProjectTimeManager"
            cd "$APP_DIR"

            echo "==> Pull latest code"
            git pull --ff-only

            echo "==> Install dependencies"
            uv pip install --python "$APP_DIR/.venv/bin/python" -r TaskManager/requirements.txt

            echo "==> Run migrations"
            $APP_DIR/.venv/bin/python3 TaskManager/manage.py migrate --noinput

            echo "==> Collect static files"
            $APP_DIR/.venv/bin/python3 TaskManager/manage.py collectstatic --noinput

            echo "==> Restart service"
            sudo systemctl restart tasktimer.service

            echo "✅ Deployment completed"

